---
title: "Models for Truck Involved Crash in Workzone"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

```{r}
library(here)
library(dplyr)
library(kableExtra)
```


```{r}
dt <- read.csv("C:/Users/ahmedf/Documents/AHMED/AHMED/RESEARCH/safety/traffic365safety247_data_analysis/rmd/truck_involved_crashes/04-model/04_x-nlogit/output/nov_2/logit_truck.csv")
```

Model 1:
========

Binary Logit model

Model Summary:
N=1827; K = 28  
log-likelihood(unrestricted): -1258.61310
log-likelihood(restricted)  : -1266.31832
Chi-squared (df = 27): 15.41044


Model 2:
========

Binary Logit model

Model Summary:
N=1827; K = 29  
log-likelihood(unrestricted): -1257.40531
log-likelihood(restricted)  : -1266.35773
Chi-squared (df = 28): 17.90484

**Notations used in the Table**:

  * "X" : variable not used in the model
  * "." : not significant

```{r}
dt %>% 
  kable() %>%
  kable_paper("hover", full_width = F) %>% 
  add_header_above(c("Model Specification " = 3, "Model 1" = 2, "Model 2" = 2))
```



